robotBCD:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: 
      p: 5.0 
      i: 20.0
      i_clamp: 100.0

  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_joint
    pid: 
      p: 5.0 
      i: 20.0
      i_clamp: 100.0
  
  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: camera_wheel_joint
    pid: 
      p: 5.0 
      i: 20.0
      i_clamp: 100.0